name: CI

on:
  pull_request:
    paths:
    - '*'
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install NG
      run: npm install -g @angular/cli
    - name: Install Dependencies
      run: npm install
    - name: list dir
      run: tree
    - name: Build
      run: cd ..
    - name: Build
      run: npm run build
